### ISSUE TITLE
Tutorials how connect to vpn from client side for most popular PC/Mobile OS

### ISSUE THREAD

**Issue by Festour** [sockeye44/instavpn#23]
It will be nice if someone write tutorials, in readme or someting else, for most popular PC(Win/Mac/Ubuntu/Linux and mobile (Android, iOS, WM) OS. Sometimes, its not easy create secure co nnection to our VPN server.

**Comment by demon101** [comment]
Из комментов хабра
Где-то час потратил, чтобы понять, как настроить клиента в Linux (fedora 21, gnome 3)
1) Нужно установить NetworkManager-l2tp пакет
2) Settings -> Networks, добавить VPN подключение с типом L2TP (Layer 2 Tunneling Protocol)
3) ввести туда IP сервера в поле Gateway и юзера + пароль, взятых с веб админки вашего vpn
4) Network Manager -> Vpn -> Connect

**Comment by schuft69** [comment]
@demon101: Could you please provide this description in english? Thanks!

**Comment by iShift** [comment]
@schuft69 
1) Install NetworkManager-l2tp package
2)  Settings -> Networks, add VPN connection with type L2TP (Layer 2 Tunneling Protocol)
3) enter  IP of your server in Gateway field and username+password (that you configure in web interface)
4) Network Manager -> Vpn -> Connect

**Comment by schuft69** [comment]
Thank you!

**Comment by sektonic** [comment]
How to install NetworkManager-l2tp package?

**Comment by sockeye44** [comment]
Sorry, this project is deprecated
