### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ddliu** [sockeye44/instavpn#29]
How to stop and uninstall it?

**Comment by sockeye44** [comment]
/etc/init.d/ipsec stop
    /etc/init.d/xl2tpd stop
    rm -rfv /opt/instavpn /usr/bin/instavpn /root/instavpn /etc/ipsec.conf.template /etc/setup-vpn.sh /etc/init/instavpn.conf
    apt-get -y remove openswan xl2tpd ppp lsof vnstat vnstati nodejs-legacy npm build-essential libssl-dev 
    echo 'exit 0' > /etc/rc.local

And remove string "* * * * * vnstati -s -i eth0 -o /opt/instavpn/public/images/vnstat.png" from crontab:

    crontab -e

**Comment by ddliu** [comment]
Great, it will be more convient if this program is distributed as a deb package for Ubuntu users.

Thank you any way!
