### ISSUE TITLE
Валидация формы

### ISSUE THREAD

**Issue by danilvalov** [sockeye44/instavpn#31]
Захожу в веб-интерфейс, перехожу на вкладку "Пользователи", нажимаю "Сохранить" и вижу:
"Все поля должны быть длиной от 6 до 32 символов и содержать только латинские буквы и цифры".

А всё потому, что при открытии формы сразу же добавляется новая пустая строка, и проходит валидацию.

Добавьте плз проверку на заполненность/не заполненность строк, и если строка пустая - пропускать её при валидации.

**Comment by sockeye44** [comment]
#31 fix
