### ISSUE TITLE
Error if server have more than one IP

### ISSUE THREAD

**Issue by iShift** [sockeye44/instavpn#33]
sudo instavpn psk set blablabla
Restarting VPN server...
failed to start openswan IKE daemon - the following error occured:
can not load config '/etc/ipsec.conf': /etc/ipsec.conf:45: syntax error, unexpected STRING, expecting $end [LOCAL IP ADRESS]
Error!

If server have more than one IP you can get that error, if fix this with manual edit /etc/ipsec.conf (remove second IP) 

All new DO droplets have 2 ip (public, private)

**Comment by sockeye44** [comment]
Fixed, thank you

**Comment by iShift** [comment]
Имхо стоит сделать выбор в админке на каком интерфейсе запускать....
