### ISSUE TITLE
I can connect L2TP, but my ip didn't change

### ISSUE THREAD

**Issue by arcticlion** [sockeye44/instavpn#35]
Hello, I'm in China, OS is OS X 10.8.5.

I can connect through L2TP, but my ip isn't vps's ip.

**Comment by sockeye44** [comment]
Hello, turn on "send all traffic" checkbox

**Comment by arcticlion** [comment]
@sockeye44  Thank you. It works.

**Comment by sockeye44** [comment]
;-)
