### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by orangeudav** [sockeye44/instavpn#36]
Can you make docker image based ubuntu? Or Dockerfile?

**Comment by pinya** [comment]
You have to try https://hub.docker.com/r/siomiz/softethervpn/

**Comment by th3m4ri0** [comment]
^ works perfectly ! 
```bash
docker run -d -p 500:500/udp -p 4500:4500/udp -p 1701:1701/tcp siomiz/softethervpn
docker ps
# get name
docker logs <trusting_voice> 
# user and pass. secret is <notasecret>
```

You can configure with the 3 parameters on the docker page.
