### ISSUE TITLE
редактирование Web

### ISSUE THREAD

**Issue by PC-Zzz** [sockeye44/instavpn#46]
Здравствуй бро, начал разбираться, хотел поменять в веб интерфейсе css .. но почему то не че гоне выходит.. в чем может быть дело,.. я чего то не догоняю повидемум .
Ибо файл зила и сайбердак показывает что файлы отредактированы . но не чеге в вебе не меняется ..  

Мб где кешируеться все это дело?

**Comment by PC-Zzz** [comment]
А в обще я бы веб интерфейс в обще не хотел выводить, исключительно через консоль работать.. как быть?

**Comment by sockeye44** [comment]
Ну, если только кэш браузера
