### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by dbaflight** [sockeye44/instavpn#48]
Hello,
I have setup instavpn on my server, it works well on windows8, but doesn't work on iOS.

**Comment by sockeye44** [comment]
Hello. Could you provide server logs?

**Comment by iikulikov** [comment]
It works for me in the latest iOS, did you choose L2TP VPN type? Firstly I accidentally chose IPSec and it didn't work of course, but it works really well now.

@sockeye44 , Очень крутой пакет, всё просто и понятно, спасибо тебе
