### ISSUE TITLE
CRITICAL: Failed installing web UI CRITICAL ERROR!

### ISSUE THREAD

**Issue by SVITY** [sockeye44/instavpn#49]
I created new Ubuntu 14.04 droplet on Digital Ocean. I got error:
14:19:49 INFO: Installing web UI...
14:19:49 CRITICAL: Failed installing web UI
CRITICAL ERROR!

**Comment by sockeye44** [comment]
Hello. Could you provide log entries after this lines?
e.g. Crash report: https://...

**Comment by SVITY** [comment]
Sorry, i destroyed this droplet. But there was not useful

**Comment by Kroid** [comment]
https://pastee.org/dfrn9

**Comment by srvthrtbh** [comment]
https://pastee.org/8ekun

**Comment by SVITY** [comment]
@sockeye44 did you fix?

**Comment by aaamoymozg** [comment]
**Can be manually fixed by executing**

`sudo mkdir --mode=755 /opt
`

**Comment by SVITY** [comment]
@aaamoymozg thanks a lot
