### ISSUE TITLE
Static IP assignment

### ISSUE THREAD

**Issue by uralik** [sockeye44/instavpn#50]
Hello,
is it possible to assign static address with respect to mac address when I connects to the server?
I use the chain of instavpn and mosh to create reliable ssh connection between machines behind NAT's, so each time dependent on who first connected - it starts to assign addresses from 172.16.1.30, so is it possible to make some changes manually in some config file to make a static list of addresses?

thanks!

**Comment by sockeye44** [comment]
Sorry, this project is deprecated
