### ISSUE TITLE
I can connect with windows but not with mikrotik and android. 

### ISSUE THREAD

**Issue by tunayuyar** [sockeye44/instavpn#54]
Hi,

Awesome working vpn thanks for it.

I can connect with windows 10 easily, but I cannot connect with my android phone (version 6.0)

Also my mikrotik router can connect but it does not resolve any adresses. 

Any help?

Thanks.

**Comment by tunayuyar** [comment]
Correction: There is only problem with android.

**Comment by sockeye44** [comment]
Hello. Unfortunately, I cannot help you with server issues. I've created nothing but installation script
