### ISSUE TITLE
HTTPS with self-signed cert by default for web panel?

### ISSUE THREAD

**Issue by insiderq** [sockeye44/instavpn#62]
Basically the question is listed in the topic. Given that WEB UI is used for generation of new users, passwords transferred over HTTP is not secure. Is that hard to implement secure HTTPS server with self-signed certificate?

**Comment by lysak0v** [comment]
Yeah, what about https? HTTP = MITM

**Comment by sockeye44** [comment]
Sorry, this project is deprecated
