### ISSUE TITLE
win10 не подключается к VPN

### ISSUE THREAD

**Issue by Lokik145** [sockeye44/instavpn#67]
Здравствуйте.

Делаю как тут https://kb.iweb.com/hc/en-us/articles/230267348 , но при подключении к серверу, у меня тупа не работает интернет, ничего не пингуется. 

Админ панель работает, пользователь есть ,общий ключ тоже, а вот с подключением беда.

**Comment by Piotrovskyi** [comment]
Это проблема виндовса

**Comment by triony** [comment]
А эту проблему виндуса можно как-то решить?
Нужно произвести какие-то специфичные настройки виндуса или требуются какие-то более серьёзные действия?
Я поднял сервис на VPS с белым IP и клиент (Win 2008) у меня также имеет белый IP. Но в итоге получаю ошибку 789. Тоже самое с клиентов Win XP, 7, 8.1 за NATом.
Что можно предпринять для решения проблемы?

**Comment by andreyvit** [comment]
У меня подключается отлично. (W10 Home) Думаю, проблема с настройками подключения.
